# Generated by Django 4.0.4 on 2022-06-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default=60, max_length=300),
            preserve_default=False,
        ),
    ]
