# Generated by Django 4.0.4 on 2022-07-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='articulos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
